name: UI Tests
on: [push, workflow_dispatch]
jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Start emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser $USER libvirt
          sudo adduser $USER kvm
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -accel on &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest

      - name: Upload UI Tests results
        uses: actions/upload-artifact@v3
        with:
          name: Instrumentation Test Results
          path: app/build/reports/androidTests/connected/