name: Unit Tests
on: [push, workflow_dispatch, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --continue

      - name: Run tests with Gradle
        run: ./gradlew testDebugUnitTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/test-results/testDebugUnitTest/
            **/build/reports/tests/testDebugUnitTest/

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: List files in test results
        run: |
          find test-results/app/build/test-results/testDebugUnitTest -maxdepth 1 -type f

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Make parse_test_results.sh executable
        run: chmod +x .github/workflows/parse_test_results.sh

      - name: Parse test results
        run: ./.github/workflows/parse_test_results.sh

      - name: Comment on PR
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: actions/github-script@v6
        with:
          script: |
            const totalTests = process.env.total_tests;
            const totalSkipped = process.env.total_skipped;
            const totalFailures = process.env.total_failures;
            const totalErrors = process.env.total_errors;
            const totalTime = process.env.total_time;
            const summary = `Tests execution summary:\nExecuted: ${totalTests}\nSkipped: ${totalSkipped}\nFailed: ${totalFailures}\nErrors: ${totalErrors}\nTime: ${totalTime}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
